### ISSUE TITLE
web.config needed

### ISSUE THREAD

**Issue by aarongustafson** [jxnblk/hello10k#3]
Node projects need a web.config file, but we have a template for you: https://a-k-apart.com/webconfigs/web.config.node.txt

**Comment by jxnblk** [comment]
Thanks! It was unclear whether the default would be provided or not. Will add one soon

**Comment by jxnblk** [comment]
I've added the template web.config file, but please let me know if there's an easy way to test this on my end or if there are any issues with the configuration
